### ISSUE TITLE
useSkill.ts TypeError (KeyError), when evaluating featureMap[path]

### ISSUE THREAD

**Issue by Fabianstw** [goethe-tcs/algo-learn#19]
**Issue Description:**
When a new feature (question or variation) is added and then subsequently removed, attempts to work with this feature result in a TypeError. This occurs because even though the feature has been removed, references to it still exist in the users log.

**Steps to Reproduce:**
- Add a new feature (question or variation)
- Test this feature (log it in your history)
- Remove the added feature
- Start any question and the error will occur 

**Occurence in Code:**
In useSkills.ts when evaluating the featureMap[path] (line 169), we can get an TypeError if the key (question) `path` does not exists anymore.

**Possible Solution:**
When we evaluate the history of the user, we should check if this question / variation still exists and otherwise delete the missing feature from the user history.

**Comment by holgerdell** [comment]
I am currently reworking this entire part of the project anyway, so I would recommend to ignore the issue for now.

**Comment by holgerdell** [comment]
I think this is fixed by 00c495a
