### ISSUE TITLE
RecursionFormula.tsx: More variations.

### ISSUE THREAD

**Issue by holgerdell** [goethe-tcs/algo-learn#7]
Variants:
- `start`: Do not vary the names, they are called f, n, and T. Only vary the number of stars.
- `names`: Same as `start`, but do vary names. (this is the only variant that currently exists)
- `return`: Instead of stars, produce an integer return value (_not_ simply the sum)
- `arithmetic`: Instead of stars, count the number of arithmetic operations (+, -, *, /)
- develop new ideas...?

**Comment by nico-miarka** [comment]
Ich bin mir nicht ganz sicher was bei return implementiert werden soll.

**Comment by holgerdell** [comment]
Beispielsweise sowas:

```
function f(int x) {
  if (x <= 1) return 2
  else return f(x/2) * f(x/2) + 6 * f(x/2)
}
```

Achso, aber was zählt man.. zum Beispiel wieder arithmetische Operationen, dann führt das zu einer Rekurrenzgleichung T(n) = 3 T(n/2) + 6
